### ISSUE TITLE
Fails install, no TensorFlow1.4?

### ISSUE THREAD

**Issue by tgryffyn** [whiteboarddan/cartoonify#12]
EDIT: I'm an idiot... don't need to go through all the manual processes for RaspberryPi, just skip down to the RPi instructions.  

I haven't fully dug into it, but spent a little time a night or two ago and on the pip install -r requirements_desktop.txt, it starts to process but fails on TensorFlow 1.4.  It seems to be indicating that 1.4 isn't available anymore.  The nearest versions mentioned are 1.1 and 1.8.  If I change it to 1.8 and try again, I get an out of memory error (sorry, at work right now, will get the exact message later, this is on a Raspberry Pi 3) and if I try 1.1, it fails on something else further down requirements_desktop.txt.   

I'm sure I can figure it out, eventually, but thought I'd check and see if there's something dumb I'm missing or just don't know about like why TensorFlow 1.4 isn't being found.

Great project, though. I look forward to getting it running and having some fun at our makerspace demo days.  Thanks!

-Trevor

**Comment by tgryffyn** [comment]
Right out of the gate:
```
Requirement already satisfied: remi==0.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 1))

Collecting tensorflow==1.4.0 (from -r requirements_desktop.txt (line 2))

Could not find a version that satisfies the requirement tensorflow==1.4.0 (from -r requirements_desktop.txt (line 2)) (from versions: 0.11.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0, 1.8.0)
No matching distribution found for tensorflow==1.4.0 (from -r requirements_desktop.txt (line 2))
```

Changing to tensflow 1.8:
```
Collecting tensorflow==1.8.0 (from -r requirements_desktop.txt (line 2))
  Downloading https://www.piwheels.org/simple/tensorflow/tensorflow-1.8.0-cp27-none-linux_armv7l.whl (67.0MB)

    99% |############################### | 67.0MB 1.7MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 605, in _download_url
    consume(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 870, in consume
    deque(iterator, maxlen=0)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError
```

Trying tensorflow 1.1.0:

```
Requirement already satisfied: remi==0.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 1))
Requirement already satisfied: tensorflow==1.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 2))
Requirement already satisfied: tensorflow-tensorboard==0.4.0rc3 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 3))
Requirement already satisfied: terminado==0.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 4))
Requirement already satisfied: testpath==0.3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 5))
Requirement already satisfied: tornado==4.5.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 6))
Requirement already satisfied: bleach==1.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 7))
Collecting cairocffi==0.8.0 (from -r requirements_desktop.txt (line 8))
Requirement already satisfied: certifi==2017.11.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 9))
Collecting cffi==1.11.2 (from -r requirements_desktop.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/c9/70/89b68b6600d479034276fed316e14b9107d50a62f5627da37fafe083fde3/cffi-1.11.2.tar.gz
Collecting chardet==3.0.4 (from -r requirements_desktop.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting click==6.7 (from -r requirements_desktop.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting cycler==0.10.0 (from -r requirements_desktop.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: enum34==1.1.6 in /usr/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 14))
Collecting gizeh==0.1.10 (from -r requirements_desktop.txt (line 15))
Requirement already satisfied: html5lib==0.9999999 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 16))
Collecting idna==2.6 (from -r requirements_desktop.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting jsonlines==1.2.0 (from -r requirements_desktop.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/4f/9a/ab96291470e305504aa4b7a2e0ec132e930da89eb3ca7a82fbe03167c131/jsonlines-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: Markdown==2.6.10 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 19))
Collecting Pillow==5.0.0 (from -r requirements_desktop.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/0f/57/25be1a4c2d487942c3ed360f6eee7f41c5b9196a09ca71c54d1a33c968d9/Pillow-5.0.0.tar.gz
Requirement already satisfied: protobuf==3.5.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 21))
Requirement already satisfied: pycparser==2.18 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 22))
Collecting pyparsing==2.2.0 (from -r requirements_desktop.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting pypng==0.0.18 (from -r requirements_desktop.txt (line 24))
Collecting python-dateutil==2.6.1 (from -r requirements_desktop.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pytz==2017.3 (from -r requirements_desktop.txt (line 26))
  Using cached https://files.pythonhosted.org/packages/a3/7f/e7d1acbd433b929168a4fb4182a2ff3c33653717195a26c1de099ad1ef29/pytz-2017.3-py2.py3-none-any.whl
Collecting requests==2.18.4 (from -r requirements_desktop.txt (line 28))
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: six==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 29))
Collecting urllib3==1.22 (from -r requirements_desktop.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Requirement already satisfied: Werkzeug==0.14.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 31))
Collecting pathlib (from -r requirements_desktop.txt (line 32))
Requirement already satisfied: mock in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 33))
Requirement already satisfied: pbr in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 34))
Requirement already satisfied: funcsigs in /usr/local/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 35))
Collecting absl-py (from -r requirements_desktop.txt (line 36))
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from -r requirements_desktop.txt (line 37))
Requirement already satisfied: wheel in /usr/lib/python2.7/dist-packages (from tensorflow==1.1.0->-r requirements_desktop.txt (line 2))
Requirement already satisfied: futures>=3.1.1; python_version < "3.2" in /usr/local/lib/python2.7/dist-packages (from tensorflow-tensorboard==0.4.0rc3->-r requirements_desktop.txt (line 3))
Requirement already satisfied: ptyprocess in /usr/local/lib/python2.7/dist-packages (from terminado==0.6->-r requirements_desktop.txt (line 4))
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado==4.5.2->-r requirements_desktop.txt (line 6))
Requirement already satisfied: backports-abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado==4.5.2->-r requirements_desktop.txt (line 6))
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf==3.5.1->-r requirements_desktop.txt (line 21))
Building wheels for collected packages: cffi, Pillow
  Running setup.py bdist_wheel for cffi ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gpSfNb/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpGuNztlpip-wheel- --python-tag cp27:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/cffi
  copying cffi/cparser.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/model.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/recompiler.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/commontypes.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/lock.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/verifier.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/__init__.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/api.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/error.py -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/_embedding.h -> build/lib.linux-armv7l-2.7/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-2.7/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-armv7l-2.7
  creating build/temp.linux-armv7l-2.7/c
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cffi
  Running setup.py clean for cffi
  Running setup.py bdist_wheel for Pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gpSfNb/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpXhZAbDpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing top-level names to src/Pillow.egg-info/top_level.txt
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext


  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-gpSfNb/Pillow/setup.py", line 804, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:

  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html



  ----------------------------------------
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build cffi Pillow
Installing collected packages: cffi, cairocffi, chardet, click, cycler, gizeh, idna, jsonlines, Pillow, pyparsing, pypng, python-dateutil, pytz, urllib3, requests, pathlib, absl-py
  Found existing installation: cffi 1.9.1
    Not uninstalling cffi at /usr/lib/python2.7/dist-packages, outside environment /usr
  Running setup.py install for cffi ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gpSfNb/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RZ_Xg0-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/cffi
    copying cffi/cparser.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/model.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/lock.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/verifier.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/__init__.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/api.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/error.py -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-armv7l-2.7/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-armv7l-2.7
    creating build/temp.linux-armv7l-2.7/c
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
  Can't rollback cffi, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gpSfNb/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RZ_Xg0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-gpSfNb/cffi/
```



Apologies... I'm not sure which one of the errors may be being fixed by the installer (Failed building wheel for cffi, Running setup.py clean for cffi?  Is that fixing itself?) and which are real errors causing further errors down the line.   My experience with stuff like this is that it's probably just one or two small errors leading to the rest.   The main thing may be that it's needing tensorflow 1.4.

Forgive any ignorance on my part. I'll be trying a few things when I get a chance, but wanted to report it in the meantime.

**Comment by tgryffyn** [comment]
Closing issue because I'm an idiot.  Leaving it here so other idiots can learn from my lack of reading.
